---
title: "Leaflet exercise"
author: "Amarins van de Voorde"
date: "1-9-2020"
output: slidy_presentation
editor_options: 
  chunk_output_type: console
---

```{r, eval=FALSE}
library(leaflet)
my_map<-leaflet() %>%
  addTiles()
my_map
```

## First map
```{r, echo=FALSE}
library(leaflet)
my_map<-leaflet() %>%
  addTiles()
my_map <- my_map %>%
  addMarkers(lat=39.2980803,lng=-76.5898801,
             popup = "Jeff Leek's Office")
my_map
```

## Second map
```{r, eval=FALSE}
set.seed(2016-04-25)
df<- data.frame(lat = runif(500, min = 39.25, max = 39.35),
                lng = runif(500, min = -76.65, max = -76.55))
df %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers()
  #addMarkers(clusterOptions = markerClusterOptions())
```

## Third map
```{r, eval=FALSE}
set.seed(2016-04-25)
df <- data.frame(lat = runif(20, min = 39.25, max = 39.35),
                lng = runif(20, min = -76.65, max = -76.55),
                col = sample(c("red", "blue", "green"), 20, replace = TRUE),
                stringsAsFactors = FALSE)
df %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(color=df$col) %>%
  addLegend(labels = LETTERS[1:3], colors = c("blue","red","green"))
```

